<a href="https://colab.research.google.com/github/kazemnejad/tensorflow-2-tutorial/blob/master/part_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensorflow 2.0 Tutorial: Part #3


Deep Learning Group, Iran University of Science and Technology,

*   Last Update: Dec 2019
*   Official Page: https://github.com/iust-deep-learning/tensorflow-2-tutorial





---




Please run the following cell before going through the rest of the tutorial.

In [0]:
from __future__ import absolute_import, division, print_function, unicode_literals

# Install TensorFlow
try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x
except Exception:
  pass

import tensorflow as tf
import numpy as np

from pprint import pprint

TensorFlow 2.x selected.


## Time Series data pipeline

---



### Exercise #1: Time Series data pipeline
A time series is a series of data points indexed in time order. One example of time series is stock prices at regular intervals of time (hourly, daily, etc.).
In this exercise we are going to create a TensorFlow dataset to generate proper input for a time series prediction problem. In a time series problem, given data points in [i : i+window], we want to predict time_series[i+window+1] as output.

Now, suppose our series is numbers in range 0 to 30:
- First, filter all non-prime numbers from dataset using **dataset.filter** functionality :


In [0]:
series = np.arange (30) #initial series


###### implementation ######
def is_prime (element):
  flag = True       
  return flag
###### implementation ######

dataset = tf.data.Dataset.from_tensor_slices(series)
dataset = dataset.filter(is_prime)
for elem in dataset:
  print(elem.numpy())



2
3
5
7
11
13
17
19
23
29



Now, create a dataset for this problem, so that

Given
- A window size

We can get 
- series[i : i+window] as input and series[i+window+1] as output in i-th iteration:

In [0]:

###### implementation ######
window_size = 3
features = ... 
labels = ...
predict_next_step = tf.data.Dataset.zip((features, labels))
###### implementation ######

for f, l in predict_next_step:
  print(f.numpy(),'-->', l.numpy())



[2 3 5] --> 7
[ 7 11 13] --> 17
[17 19 23] --> 29


## References


---

